export enum LocalStorageEnum {
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN'
  /*  EMAIL = 'EMAIL',
  USER_ID = 'USER_ID',
  USER_FIRST_NAME = 'USER_FIRST_NAME',
  USER_LAST_NAME = 'USER_LAST_NAME',
  USER_PERMISSIONS_ENUM_ARRAY = 'USER_PERMISSIONS_ENUM_ARRAY',
  CONTEXT = 'CONTEXT', */
}
